version: '3.3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    network_mode: 'host'
    restart: always
    privileged: true
    user: root
    ports:
     - 8080:8080
    #  - 50000:50000
    container_name: jenkins-master
    volumes:
      - /root/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
