- name: Check if docker is installed or install it if not
  include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: Add "vagrant" user to "docker" group
  user:
    name: vagrant
    groups: docker
    append: true

- name: Check if docker is active
  service:
    name: docker
    state: started
    enabled: true

- name: Add the user "jenkins" with home directory and other staff
  user:
    name: jenkins
    shell: /bin/bash
    groups: docker
    expires: -1
    create_home: yes
    append: yes
    password: "$6$rounds=656000$ZcSm1.k6rhOfzYWP$MGBlBLLgGTFSIt29JSree7YrIFrZW2dr7XuzGpdHD58xl.Ope42geR.Eva2I4IIS6c/XQ.Mw3zwPLgj8IdqmO/"

- name: Create .ssh directory for jenkins user
  file:
    path: "/home/jenkins/.ssh"
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0700'

- name: Copy project files to default destination dir
  copy:
    src: "{{ item }}"
    dest: "{{ ssh_key_dest_dir }}/authorized_keys"
    owner: jenkins
    group: jenkins
    mode: '0644'
  loop:
    - "{{ ssh_pubkey }}"

- name: Configure sshd
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{item.key}}"
    line: "{{item.key}} {{item.value}}"
    state: present
  loop:
    - { key: "PermitRootLogin", value: "no" }
    - { key: "PasswordAuthentication", value: "no" } 
    - { key: "PubkeyAuthentication", value: "yes" }
  notify:
    - restart sshd


