all:
  children:
    master:
      hosts:
        jenkins_master:
          ansible_host: 127.0.0.1
          ansible_port: 2200
          ansible_user: vagrant
          ansible_private_key_file: /home/${USER}/.vagrant.d/insecure_private_keys/vagrant.key.rsa
    slave:
      hosts:
        jenkins_slave:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          ansible_user: vagrant
          ansible_private_key_file: /home/${USER}/.vagrant.d/insecure_private_keys/vagrant.key.rsa